### ISSUE TITLE
No such file or directory: '/etc/network/interfaces.d/*' while file is interfaces

### ISSUE THREAD

**Issue by mehrdad1373pedramfar** [pylover/network-interfaces#9]
```
Traceback (most recent call last):
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/application.py", line 64, in __call__
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     response_body = self.__root__(*remaining_paths)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/restfulpy/controllers.py", line 18, in __call__
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return super().__call__(*remaining_paths)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/controllers.py", line 83, in __call__
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return self._serve_handler(handler, remaining_paths)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/controllers.py", line 78, in _serve_handler
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return handler(*remaining_paths, **kwargs)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/controllers.py", line 83, in __call__
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return self._serve_handler(handler, remaining_paths)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/controllers.py", line 78, in _serve_handler
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return handler(*remaining_paths, **kwargs)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/controllers.py", line 83, in __call__
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return self._serve_handler(handler, remaining_paths)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/controllers.py", line 78, in _serve_handler
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return handler(*remaining_paths, **kwargs)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/controllers.py", line 83, in __call__
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return self._serve_handler(handler, remaining_paths)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/controllers.py", line 78, in _serve_handler
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return handler(*remaining_paths, **kwargs)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/nanohttp/decorators.py", line 52, in wrapper
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     result = func(*args, **kwargs)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/restfulpy/authorization.py", line 21, in wrapper
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return func(*args, **kwargs)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/ursa/ursa/controllers/interface.py", line 40, in get
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     interface = self.ensure_default_interface()
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/ursa/ursa/controllers/interface.py", line 31, in ensure_default_interface
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     interfaces = interfaces or self.ensure_interfaces()
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/ursa/ursa/controllers/interface.py", line 28, in ensure_interfaces
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     return InterfacesFile(settings.network.interfaces_file)
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/network_interfaces/interface_file.py", line 71, in __init__
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     self.sub_files.append(InterfacesFile(subfile[0], source=subfile[1]))
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:   File "/usr/local/lib/python3.6/site-packages/network_interfaces/interface_file.py", line 37, in __init__
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]:     with open(self.absolute_filename) as f:
Feb  1 19:14:58 sandbox-ubuntu gunicorn[1871]: FileNotFoundError: [Errno 2] No such file or directory: '/etc/network/interfaces.d/*'
Feb  1 19:15:01 sandbox-ubuntu CRON[2067]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
```

**Comment by pylover** [comment]
#10
